### ISSUE TITLE
Update dependencies to support phoenix_ecto 4.1

### ISSUE THREAD

**Issue by alanvardy** [pow-auth/pow_assent#105]
Hello!

Thank you for the libraries and all the great work you are doing. I'm using pow on all my projects and loving it :)

I am hoping to update my dependencies to include a new library and being blocked by pow_assent's requirement for `{:phoenix_ecto, "~> 4.0.0", only: [:dev, :test]},`

Phoenix Ecto reached 4.1 recently and it doesn't look like they made any breaking changes (thank you semantic versioning :) ) https://github.com/phoenixframework/phoenix_ecto/blob/master/CHANGELOG.md

I'm not super knowledgeable when it comes to auth, but I would be happy to open a PR on this if it makes your life easier.

Cheers!

**Comment by danschultzer** [comment]
Thanks a lot!

Dependencies are build [with `:prod` env](https://hexdocs.pm/mix/master/Mix.Tasks.Deps.html#module-dependency-definition-options), so this shouldn't block you since it's a dev dependency for when working directly on the library. Can you post the error you get?

I'll still update the dep, but that requirement definitely shouldn't affect building your project.

**Comment by alanvardy** [comment]
Hi @danschultzer , I think you are completely correct :slightly_smiling_face: 

After disabling pow_assent temporarily I found that it was because the new library [ex_audit](https://github.com/ZennerIoT/ex_audit) wants Ecto 3.2 while a number of my other libraries want me to stick with 3.1

Looks like I latched on to the first error message I saw too early :)

Thank you a lot for the quick response and all that you do!
