### ISSUE TITLE
Server was unreachable with Assent.HTTPAdapter.Httpc.

### ISSUE THREAD

**Issue by jagoanmamah** [pow-auth/pow_assent#173]
![0eb0c6e2-2649-4ffc-9176-2aa08017fcec](https://user-images.githubusercontent.com/25195185/82001710-fe54ab80-9685-11ea-9a4f-895488247cf8.png)

**Comment by danschultzer** [comment]
Can you copy-paste the full error? It seems like there's an issue with the SSL handshake, do you have `certify` and `ssl_verify_fun` in your deps as outlined [in the readme](https://github.com/pow-auth/pow_assent#installation):

```elixir
defp deps do
  [
    # ...
    {:pow_assent, "~> 0.4.7"},
    {:certifi, "~> 2.4"},
    {:ssl_verify_fun, "~> 1.1"}
  ]
end
```

**Comment by jagoanmamah** [comment]
Failed with the following error:
{:failed_connect, [{:to_address, {'www.googleapis.com', 443}}, {:inet, [:inet], {:tls_alert, {:handshake_failure, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1840 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}}]}

URL: https://www.googleapis.com/oauth2/v4/token

**Comment by danschultzer** [comment]
Hmm, this could be due to many things.

I tested this locally and it works as expected. You can try it yourself running `iex -S mix` in your app dir and then call the following method:

```elixir
Assent.Strategy.request(:post, "https://www.googleapis.com/oauth2/v4/token", "", [], [http_adapter: Assent.HTTPAdapter.Httpc])
```

It should return a `Assent.HTTPAdapter.HTTPResponse` struct, rather than `Assent.RequestError` with the handshake error.

Two questions:

1. What OTP version are you running on?
2. Do you have any `:http_adapter` config set? If `:ssl` key is set it would override [the default ssl settings](https://github.com/pow-auth/assent/blob/v0.1.10/lib/assent/http_adapter/httpc.ex#L85-L94).

**Comment by jagoanmamah** [comment]
I don't have :http_adapter

![Screenshot from 2020-05-15 19-21-15](https://user-images.githubusercontent.com/25195185/82050073-afd4fa80-96e1-11ea-8d4c-90e97171bc7e.png)

**Comment by danschultzer** [comment]
Ok, I can reproduce it now. I was running on OTP 22.2. On OTP 23 it fails. Let me figure out why.

**Comment by danschultzer** [comment]
Assent `v0.1.11` has been released. Run `mix deps.update assent` and it should be working again with OTP 23 😄
