### ISSUE TITLE
Strategy failed with error: %Assent.Config.MissingKeyError{message: "Key `:session_params` not found in config"}

### ISSUE THREAD

**Issue by arashout** [pow-auth/pow_assent#217]
Hi, 

I'm trying to make a simple toy-app using this library but running into some trouble trying to integrate [Strava](https://www.strava.com/)

When I press the generated `Sign in with Strava` link from I get the following error:
`Strategy failed with error: %Assent.Config.MissingKeyError{message: "Key `:session_params` not found in config"}`

If I try to instead sign-in first using an existing user and then click it I get a different error:

`
[error] Strategy failed with error: %Assent.RequestError{error: :invalid_server_response, message: "Server responded with status: 400\n\nHeaders:\ncache-control: no-cache\nconnection: keep-alive\ndate: Tue, 14 Sep 2021 07:28:08 GMT\nvia: 1.1 linkerd, 1.1 linkerd\nserver: nginx/1.19.5\nvary: Origin\ncontent-length: 104\ncontent-type: application/json; charset=utf-8\nstatus: 400 Bad Request\nx-request-id: 6371f662-4d57-4183-b31d-d82bfb70be72\nreferrer-policy: strict-origin-when-cross-origin\nx-frame-options: DENY\nx-xss-protection: 1; mode=block\nx-download-options: noopen\nx-content-type-options: nosniff\nx-permitted-cross-domain-policies: none\n\nBody:\n%{\"errors\" => [%{\"code\" => \"invalid\", \"field\" => \"client_secret\", \"resource\" => \"Application\"}], \"message\" => \"Bad Request\"}\n"}
`

Which would maybe indicate that my CLIENT_SECRET is wrong but I don't that's the case because I authenticated successfully using a different library.

My `config.exs`

```elixir
config :habitica_integrations, :pow_assent,
  providers: [
    strava: [
      site: "https://www.strava.com",
      client_id: System.fetch_env!("STRAVA_CLIENT_ID"),
      client_secret: System.fetch_env!("STRAVA_CLIENT_SECRET"),
      authorization_params: [
        scope: "activity:read_all",
        redirect_uri: System.fetch_env!("STRAVA_REDIRECT_URI") <> "/auth/strava/callback",
        response_type: "code"
      ],
      strategy: Assent.Strategy.OAuth2
    ]
  ]
```

What `session_params` am I supposed to provide?

**Comment by danschultzer** [comment]
You should add `auth_method: :client_secret_post` to your config, as otherwise the client secret will not be submitted in a POST request.

As for the `:session_params` do you use a custom controller?

**Comment by MMore** [comment]
Hello, interesting I sometimes see that error too. But it looks like it's only for some users...
I am using Slack for SSO.

Any ideas?

**Comment by baree99** [comment]
I am seeing that error too, around 1 out of 10 times - using Google for signing in. Same user can sign in without any problems and have this next time (and when trying again the user is able to sign in).

Any ideas?

**Comment by baree99** [comment]
We managed to solve it. We run our services on Kubernetes and have multiple pods running the same service. The session params are not stored in a cookie, so when the callback is not happening on the same pod as the initial call to google, the session params are not available.

The solution was to use Redis to store session params.

**Comment by danschultzer** [comment]
@erasmas it looks like you are using the default ETS cache? It'll be cleared on restart (so very easy to reproduce if this is the case). Instead you must switch to a persistent store as detailed here: https://github.com/pow-auth/pow#cache-store

**Comment by erasmas** [comment]
> @erasmas it looks like you are using the default ETS cache? It'll be cleared on restart (so very easy to reproduce if this is the case). Instead you must switch to a persistent store as detailed here: https://github.com/pow-auth/pow#cache-store

Thank you! I tried to see if the issue is indeed caused by in-memory cache by logging in, restarting the server and trying to login back again but it doesn't reproduce for me. I did follow your advice though, to replace in-memory store with a persistent store. I didn't want to introduce yet another service dependency such as Mnezia or Redis, so I used https://github.com/ZennerIoT/pow_postgres_store.

**Comment by danschultzer** [comment]
Hopefully the persistent cache did the trick!

BTW there's a Strava strategy in the latest assent release you can use now: https://github.com/pow-auth/assent/blob/v0.2.7/lib/assent/strategies/strava.ex

---

For anyone who needs to debug an issue with the `:session_params` not existing in the config, this is how it all works under the hood:

1. On both `/auth/:provider/new` and `/auth/:provider/callback` before anything else happens the session is initialized (this is the same way `Plug.Session` works):
    - `auth_session` cookie is loaded and verified.
    - The cookie value is used to fetch the pow assent session (this includes the `:session_params`).
    - The pow assent session and `auth_session` cookie are deleted to prevent replay.
    - A `Plug.Conn.register_before_send/2` callback is set to store a new session and set `auth_session` cookie if `pow_assent_session_info: :write` exists in `conn.private`.

2. On `/auth/:provider/new` before redirecting to provider
    - If the strategy returns `:session_params` set them in `conn.private` to be stored with the `Plug.Conn.register_before_send/2` callback. This will create a key in the session cache and a signed cookie with that key as value.

3. On `/auth/:provider/callback` before processing the params
    - If `:session_params` were loaded from session via the cookie, assign them in the config being passed to the strategy.

The above issue would mean that the last step didn't happen because `:session_params` was not set in the config. That would point to the cookie or session not being loaded.
